apiVersion: apps/v1
kind: Deployment
metadata:
  name: wanderlust-devsecops-backend
spec:
  selector:
    matchLabels:
      app: wanderlust-backend
  template:
    metadata:
      labels:
        app: wanderlust-backend
    spec:
      containers:
      - name: backend
        image: amaurya07/wanderlust_backend:3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
          - name: MONGODB_URI
            value: mongodb://test:password@mongo-nodeport-svc:27017/wanderlust
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: MONGO_USERNAME
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: MONGO_PASSWORD
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: wanderlust-cm
                key: PORT
          # - name: MONGODB_URI
          #   valueFrom:
          #     configMapKeyRef:
          #       name: wanderlust-cm
          #       key: MONGODB_URI
          - name: REDIS_URL
            valueFrom:
              configMapKeyRef:
                name: wanderlust-cm
                key: REDIS_URL
          - name: FRONTEND_URL
            valueFrom:
              configMapKeyRef:
                name: wanderlust-cm
                key: FRONTEND_URL
          - name: BACKEND_URL
            valueFrom:
              configMapKeyRef:
                name: wanderlust-cm
                key: BACKEND_URL
          - name: ACCESS_COOKIE_MAXAGE
            valueFrom:
              configMapKeyRef:
                name: wanderlust-cm
                key: ACCESS_COOKIE_MAXAGE
          - name: ACCESS_TOKEN_EXPIRES_IN
            valueFrom:
              configMapKeyRef:
                name: wanderlust-cm
                key: ACCESS_TOKEN_EXPIRES_IN
          - name: REFRESH_COOKIE_MAXAGE
            valueFrom:
              configMapKeyRef:
                name: wanderlust-cm
                key: REFRESH_COOKIE_MAXAGE
          - name: REFRESH_TOKEN_EXPIRES_IN
            valueFrom:
              configMapKeyRef:
                name: wanderlust-cm
                key: REFRESH_TOKEN_EXPIRES_IN
          - name: JWT_SECRET
            valueFrom:
              configMapKeyRef:
                name: wanderlust-cm
                key: JWT_SECRET
          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                name: wanderlust-cm
                key: NODE_ENV
          - name: CORS_ORIGIN
            valueFrom:
              configMapKeyRef:
                name: wanderlust-cm
                key: CORS_ORIGIN
