apiVersion: v1
kind: Service
metadata:
  labels:
    app: wanderlust-db
  name: mongo-nodeport-svc
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
    nodePort: 32000
  selector:
    app: wanderlust-db
  type: NodePort