apiVersion: apps/v1
kind: Deployment
metadata:
  name: wanderlust-db
spec:
  selector:
    matchLabels:
      app: wanderlust-db
  template:
    metadata:
      labels:
        app: wanderlust-db
    spec:
      containers:
      - name: mongo
        image: mongo
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
            - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
                name: mongo-creds
                key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
                name: mongo-creds
                key: password
        volumeMounts:
            - name: mongodb-storage
              mountPath: /data/mongo
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc

