apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: pvc-a6aa1ade-eb28-4e3b-9f67-efa5738df867
    fsType: ext4
