apiVersion: apps/v1
kind: Deployment
metadata:
  name: wanderlust-devsecops
spec:
  selector:
    matchLabels:
      app: wanderlust-frontend
  template:
    metadata:
      labels:
        app: wanderlust-frontend
    spec:
      containers:
      - name: frontend
        image: amaurya07/wanderlust_frontend:1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5173
